project:
  type: website

website:
  title: "IS415-GAA"
  
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3-1"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03-1.html"
        - text: "Hands-on Exercise 3-2"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03-2.html"
        - text: "Hands-on Exercise 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "Hands-on Exercise 5-1"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05-1.html"
        - text: "Hands-on Exercise 5-2"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05-2.html"
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise 2"
          href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
        - text: "In-class Exercise 3 KDE"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03-KDE.html"
        - text: "In-class Exercise 3 NKDE"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03-NKDE.html"
        - text: "In-class Exercise 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
    - text: "Take-home Exercise"
      menu:
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      
  page-footer: 
    left: "Russell Tio" 
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/russelltio/
      #- icon: github
      #  href: https://github.com/russelltjh
    
  back-to-top-navigation: true

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

